/* ============================================================
   Alchemist — data model + Gin content
   All cocktail recipes are real, classic specs.
   `color` is each drink's actual appearance, in OKLCH, used as
   data (the liquid swatch) — not decoration.
   ============================================================ */

export type Strength = 1 | 2 | 3; // 1 sessionable · 2 medium · 3 spirit-forward
export type Difficulty = "Easy" | "Medium" | "Advanced";

export interface TastingNote {
  label: string;
  detail: string;
}

export interface Serve {
  name: string;
  blurb: string;
  /** glyph kind for the small illustrated icon */
  glass: "neat" | "rocks" | "highball" | "coupe";
}

export interface Mixer {
  name: string;
  note: string;
  /** the swatch color of the mixer */
  color: string;
}

export interface Cocktail {
  slug: string;
  name: string;
  tagline: string;
  /** actual liquid color, OKLCH */
  color: string;
  /** lighter tint of the liquid, for the swatch base */
  colorSoft: string;
  ingredients: string[];
  method: string;
  glass: string;
  strength: Strength;
  difficulty: Difficulty;
  /** signature note that makes it worth trying */
  hook: string;
}

export interface Spirit {
  name: string;
  /** data-theme palette applied to <html> while on this spirit's page */
  spiritTheme: string;
  binomial: string;
  abv: string;
  origin: string;
  intro: string;
  character: string;
  notes: TastingNote[];
  serves: Serve[];
  mixers: Mixer[];
  cocktails: Cocktail[];
}

export interface SpiritTeaser {
  name: string;
  slug: string;
  tagline: string;
  /** representative liquid color, OKLCH */
  color: string;
  colorSoft: string;
  cocktails: number;
  available: boolean;
}

/** The spirit shelf shown on the landing page. */
export const spiritShelf: SpiritTeaser[] = [
  {
    name: "Gin",
    slug: "gin",
    tagline: "Botanical, bright, endlessly mixable",
    color: "oklch(0.62 0.13 235)",
    colorSoft: "oklch(0.86 0.07 235)",
    cocktails: 12,
    available: true,
  },
  {
    name: "Whisky",
    slug: "whisky",
    tagline: "Smoke, oak and slow evenings",
    color: "oklch(0.6 0.13 65)",
    colorSoft: "oklch(0.82 0.08 65)",
    cocktails: 12,
    available: true,
  },
  {
    name: "Rum",
    slug: "rum",
    tagline: "Sugarcane warmth, island to glass",
    color: "oklch(0.55 0.12 50)",
    colorSoft: "oklch(0.8 0.08 50)",
    cocktails: 12,
    available: true,
  },
  {
    name: "Tequila",
    slug: "tequila",
    tagline: "Agave, earth and a citrus edge",
    color: "oklch(0.8 0.11 120)",
    colorSoft: "oklch(0.9 0.06 120)",
    cocktails: 12,
    available: true,
  },
  {
    name: "Vodka",
    slug: "vodka",
    tagline: "A clean canvas for anything",
    color: "oklch(0.9 0.02 250)",
    colorSoft: "oklch(0.95 0.012 250)",
    cocktails: 12,
    available: true,
  },
];

export const gin: Spirit = {
  name: "Gin",
  spiritTheme: "indigo",
  binomial: "Juniperus communis",
  abv: "37.5–47%",
  origin: "England & the Low Countries",
  intro:
    "A neutral spirit reborn through botanicals — juniper at its heart, then a chosen cast of citrus peel, root, seed and flower. Distillers treat it like a recipe, which makes gin the most expressive base a mixer can reach for.",
  character:
    "Crisp, aromatic and pine-bright, with a backbone of juniper and a long citrus finish. London Dry is bone-dry and assertive; contemporary gins lean floral or citrus-forward.",
  notes: [
    { label: "Juniper", detail: "Pine-fresh, resinous — the signature" },
    { label: "Citrus peel", detail: "Lemon & bitter orange, bright and clean" },
    { label: "Coriander", detail: "Warm, lemony spice" },
    { label: "Angelica root", detail: "Earthy, dry, holds it all together" },
    { label: "Orris", detail: "Soft violet, a floral hush" },
  ],
  serves: [
    {
      name: "Neat",
      blurb:
        "Reserved for navy-strength and barrel-aged bottlings. Room temperature, a small pour, no rush.",
      glass: "neat",
    },
    {
      name: "On the rocks",
      blurb:
        "One large cube, a twist of lemon. Lets a botanical-rich gin open up as it chills.",
      glass: "rocks",
    },
    {
      name: "Gin & Tonic",
      blurb:
        "The default for a reason. Chilled tonic, plenty of ice, a wedge of lime — the botanicals do the work.",
      glass: "highball",
    },
    {
      name: "Martini",
      blurb:
        "Gin, dry vermouth, stirred cold, lemon twist or olive. The clearest mirror a gin can be poured into.",
      glass: "coupe",
    },
  ],
  mixers: [
    { name: "Tonic water", note: "Quinine bitterness, lifts juniper", color: "oklch(0.97 0.012 200)" },
    { name: "Dry vermouth", note: "Herbal, dry — the Martini's other half", color: "oklch(0.92 0.05 105)" },
    { name: "Sweet vermouth", note: "Rich, bitter-sweet, builds Negronis", color: "oklch(0.5 0.14 35)" },
    { name: "Soda water", note: "Clean lengthener, keeps it crisp", color: "oklch(0.98 0.004 220)" },
    { name: "Fresh lemon", note: "Sharp acid, the classic balancer", color: "oklch(0.9 0.13 100)" },
    { name: "Fresh lime", note: "Rounder, greener acidity", color: "oklch(0.88 0.13 130)" },
    { name: "Elderflower", note: "Floral, honeyed, summery", color: "oklch(0.93 0.06 110)" },
    { name: "Cucumber", note: "Cool and clean, loves a floral gin", color: "oklch(0.9 0.09 140)" },
    { name: "Campari", note: "Bitter orange backbone", color: "oklch(0.55 0.19 30)" },
    { name: "Ginger ale", note: "Warm spice, a little sweet", color: "oklch(0.88 0.08 90)" },
  ],
  cocktails: [
    {
      slug: "negroni",
      name: "Negroni",
      tagline: "Equal parts, infinite depth",
      color: "oklch(0.53 0.18 33)",
      colorSoft: "oklch(0.82 0.1 40)",
      ingredients: ["30ml gin", "30ml Campari", "30ml sweet vermouth", "Orange peel"],
      method: "Stir over ice, strain into a rocks glass with a large cube. Express orange peel.",
      glass: "Rocks",
      strength: 3,
      difficulty: "Easy",
      hook: "Bitter, bracing, perfectly balanced — the apéritif other apéritifs answer to.",
    },
    {
      slug: "martini",
      name: "Dry Martini",
      tagline: "The clearest mirror",
      color: "oklch(0.95 0.035 110)",
      colorSoft: "oklch(0.97 0.02 110)",
      ingredients: ["60ml gin", "10ml dry vermouth", "Lemon twist or olive"],
      method: "Stir hard with ice until ice-cold, strain into a chilled coupe. Garnish.",
      glass: "Coupe",
      strength: 3,
      difficulty: "Medium",
      hook: "Nothing to hide behind — the test every great gin wants to pass.",
    },
    {
      slug: "gin-tonic",
      name: "Gin & Tonic",
      tagline: "Effortless, endlessly tweakable",
      color: "oklch(0.96 0.02 200)",
      colorSoft: "oklch(0.98 0.012 200)",
      ingredients: ["50ml gin", "150ml tonic water", "Lime wedge", "Plenty of ice"],
      method: "Build over ice in a highball, add tonic gently, garnish to match the gin's botanicals.",
      glass: "Highball",
      strength: 1,
      difficulty: "Easy",
      hook: "The benchmark long drink. Get the ice and the ratio right and it sings.",
    },
    {
      slug: "tom-collins",
      name: "Tom Collins",
      tagline: "Gin lemonade, grown up",
      color: "oklch(0.93 0.06 100)",
      colorSoft: "oklch(0.96 0.035 100)",
      ingredients: ["50ml gin", "25ml lemon juice", "15ml sugar syrup", "Soda water"],
      method: "Shake gin, lemon and syrup, strain into an ice-filled Collins glass, top with soda.",
      glass: "Collins",
      strength: 1,
      difficulty: "Easy",
      hook: "Tall, fizzy and citrus-bright — the original cooler.",
    },
    {
      slug: "gimlet",
      name: "Gimlet",
      tagline: "Two ingredients, total clarity",
      color: "oklch(0.9 0.09 132)",
      colorSoft: "oklch(0.94 0.05 132)",
      ingredients: ["60ml gin", "20ml lime cordial", "Lime wheel"],
      method: "Shake with ice, double-strain into a chilled coupe. Garnish with a lime wheel.",
      glass: "Coupe",
      strength: 2,
      difficulty: "Easy",
      hook: "Tart, clean and a little nautical — proof that less is more.",
    },
    {
      slug: "aviation",
      name: "Aviation",
      tagline: "A drink the colour of dusk",
      color: "oklch(0.74 0.1 305)",
      colorSoft: "oklch(0.86 0.06 305)",
      ingredients: ["45ml gin", "15ml maraschino", "15ml lemon juice", "1 bar spoon crème de violette"],
      method: "Shake all with ice, double-strain into a chilled coupe. Optional brandied cherry.",
      glass: "Coupe",
      strength: 2,
      difficulty: "Advanced",
      hook: "Floral, sour and that unmistakable pale-violet sky.",
    },
    {
      slug: "french-75",
      name: "French 75",
      tagline: "Gin meets Champagne",
      color: "oklch(0.92 0.07 95)",
      colorSoft: "oklch(0.95 0.04 95)",
      ingredients: ["30ml gin", "15ml lemon juice", "10ml sugar syrup", "Champagne"],
      method: "Shake gin, lemon and syrup, strain into a flute, top with chilled Champagne.",
      glass: "Flute",
      strength: 2,
      difficulty: "Medium",
      hook: "Named after a field gun — it hits with that kind of celebration.",
    },
    {
      slug: "last-word",
      name: "Last Word",
      tagline: "Equal parts, electric green",
      color: "oklch(0.78 0.14 138)",
      colorSoft: "oklch(0.88 0.08 138)",
      ingredients: ["22ml gin", "22ml green Chartreuse", "22ml maraschino", "22ml lime juice"],
      method: "Shake all equally with ice, double-strain into a chilled coupe.",
      glass: "Coupe",
      strength: 3,
      difficulty: "Advanced",
      hook: "Herbal, sharp and complex — a Prohibition ghost worth resurrecting.",
    },
    {
      slug: "clover-club",
      name: "Clover Club",
      tagline: "Silken, raspberry-pink",
      color: "oklch(0.77 0.13 8)",
      colorSoft: "oklch(0.88 0.07 8)",
      ingredients: ["45ml gin", "15ml lemon juice", "15ml raspberry syrup", "Egg white"],
      method: "Dry-shake, then shake with ice, double-strain into a coupe. Float raspberries.",
      glass: "Coupe",
      strength: 2,
      difficulty: "Advanced",
      hook: "A pre-Prohibition stunner with a cloud of foam on top.",
    },
    {
      slug: "bramble",
      name: "Bramble",
      tagline: "A hedgerow in a glass",
      color: "oklch(0.5 0.15 350)",
      colorSoft: "oklch(0.78 0.11 350)",
      ingredients: ["50ml gin", "25ml lemon juice", "10ml sugar syrup", "15ml crème de mûre"],
      method: "Shake gin, lemon and syrup; pour over crushed ice; drizzle blackberry liqueur to bleed through.",
      glass: "Rocks",
      strength: 2,
      difficulty: "Medium",
      hook: "Modern British classic — tart, fruity and beautiful as it bleeds.",
    },
    {
      slug: "bees-knees",
      name: "Bee's Knees",
      tagline: "Honey softens the edges",
      color: "oklch(0.86 0.11 88)",
      colorSoft: "oklch(0.92 0.06 88)",
      ingredients: ["50ml gin", "20ml lemon juice", "15ml honey syrup"],
      method: "Shake with ice, double-strain into a chilled coupe. Lemon twist.",
      glass: "Coupe",
      strength: 2,
      difficulty: "Easy",
      hook: "Prohibition's friendliest sour — honey rounds the citrus beautifully.",
    },
    {
      slug: "southside",
      name: "Southside",
      tagline: "Mint, lime, brightness",
      color: "oklch(0.88 0.1 140)",
      colorSoft: "oklch(0.93 0.06 140)",
      ingredients: ["50ml gin", "25ml lime juice", "20ml sugar syrup", "Mint leaves"],
      method: "Muddle mint, shake all with ice, double-strain into a coupe. Mint sprig.",
      glass: "Coupe",
      strength: 2,
      difficulty: "Medium",
      hook: "Like a Mojito's cooler, sharper cousin — herbal and clean.",
    },
  ],
};

/* ------------------------------------------------------------
   Stub spirits — minimal entries so the dynamic route resolves
   while the full guides are still being written.
   ------------------------------------------------------------ */
export const whisky: Spirit = {
  name: "Whisky",
  spiritTheme: "spritz",
  binomial: "Hordeum vulgare",
  abv: "40–46%",
  origin: "Scotland & Ireland",
  intro:
    "Grain spirit transformed by cask and time — barley, corn or rye distilled, then aged in oak until it turns gold. Where gin is built from botanicals, whisky is built from patience, and every region writes its accent into the spirit.",
  character:
    "Warm and layered, from the peat-smoke and brine of Islay to the vanilla-and-caramel sweetness of bourbon and the dry spice of rye. A few drops of water open it up; the years in oak gave it everything else.",
  notes: [
    { label: "Malted barley", detail: "Cereal sweetness — the foundation grain" },
    { label: "Oak", detail: "Vanilla, spice and colour drawn from the cask" },
    { label: "Peat smoke", detail: "Earthy, medicinal, maritime — the Islay signature" },
    { label: "Dried fruit", detail: "Raisin and fig from sherry-cask ageing" },
    { label: "Honey", detail: "Heather-sweet, rounding the spirit's edges" },
  ],
  serves: [
    {
      name: "Neat",
      blurb:
        "The purist's pour. Room temperature in a tulip glass, a small measure — let the nose lead before the first sip.",
      glass: "neat",
    },
    {
      name: "On the rocks",
      blurb:
        "One large cube to chill without flooding. Softens a high-proof bourbon and slowly unlocks new notes.",
      glass: "rocks",
    },
    {
      name: "Highball",
      blurb:
        "Whisky and cold soda over plenty of ice. The Japanese serve of choice — light, crisp and endlessly drinkable.",
      glass: "highball",
    },
    {
      name: "Hot Toddy",
      blurb:
        "Whisky, honey, lemon and hot water. The remedy for a cold night, spiced with clove and cinnamon.",
      glass: "rocks",
    },
  ],
  mixers: [
    { name: "Soda water", note: "Clean lengthener for the perfect highball", color: "oklch(0.98 0.004 220)" },
    { name: "Cola", note: "Sweet, caramel — the easy crowd-pleaser", color: "oklch(0.32 0.06 50)" },
    { name: "Ginger ale", note: "Warm spice, a little sweet", color: "oklch(0.88 0.08 90)" },
    { name: "Ginger beer", note: "Spicier, cloudier, builds a Mule", color: "oklch(0.85 0.07 85)" },
    { name: "Sweet vermouth", note: "Rich and bitter-sweet — the Manhattan's half", color: "oklch(0.5 0.14 35)" },
    { name: "Angostura bitters", note: "Aromatic spice, the cocktail seasoning", color: "oklch(0.42 0.12 32)" },
    { name: "Fresh lemon", note: "Sharp acid that lifts the sour", color: "oklch(0.9 0.13 100)" },
    { name: "Honey", note: "Floral sweetness, loves a Toddy", color: "oklch(0.8 0.12 85)" },
    { name: "Maple syrup", note: "Deep amber, a richer old-fashioned", color: "oklch(0.58 0.11 68)" },
    { name: "Coffee", note: "Roasted depth — the Irish coffee base", color: "oklch(0.3 0.05 55)" },
  ],
  cocktails: [
    {
      slug: "old-fashioned",
      name: "Old Fashioned",
      tagline: "Spirit, sugar, bitters, time",
      color: "oklch(0.55 0.12 62)",
      colorSoft: "oklch(0.82 0.08 62)",
      ingredients: ["50ml bourbon or rye", "1 sugar cube", "2 dashes Angostura bitters", "Orange peel"],
      method: "Muddle sugar with bitters and a splash of water, add whisky and a large cube, stir to chill. Express orange peel over the top.",
      glass: "Rocks",
      strength: 3,
      difficulty: "Easy",
      hook: "The original cocktail — nothing to hide behind, nothing wasted.",
    },
    {
      slug: "manhattan",
      name: "Manhattan",
      tagline: "Rye and vermouth in tension",
      color: "oklch(0.45 0.13 38)",
      colorSoft: "oklch(0.8 0.09 38)",
      ingredients: ["50ml rye whiskey", "25ml sweet vermouth", "2 dashes Angostura bitters", "Brandied cherry"],
      method: "Stir with ice until well chilled, strain into a chilled coupe. Garnish with a brandied cherry.",
      glass: "Coupe",
      strength: 3,
      difficulty: "Easy",
      hook: "The benchmark stirred drink — spice, sweetness and bitters in balance.",
    },
    {
      slug: "whiskey-sour",
      name: "Whiskey Sour",
      tagline: "Tart, silky, perfectly balanced",
      color: "oklch(0.8 0.11 88)",
      colorSoft: "oklch(0.9 0.06 88)",
      ingredients: ["50ml bourbon", "25ml lemon juice", "20ml sugar syrup", "Egg white", "Angostura bitters"],
      method: "Dry-shake with egg white, then shake hard with ice. Strain over fresh ice and dash bitters across the foam.",
      glass: "Rocks",
      strength: 2,
      difficulty: "Medium",
      hook: "The template every sour follows — and a cloud of foam on top.",
    },
    {
      slug: "boulevardier",
      name: "Boulevardier",
      tagline: "A Negroni gone bourbon",
      color: "oklch(0.48 0.15 35)",
      colorSoft: "oklch(0.8 0.1 38)",
      ingredients: ["35ml bourbon", "30ml Campari", "30ml sweet vermouth", "Orange peel"],
      method: "Stir with ice, strain over a large cube in a rocks glass. Express orange peel.",
      glass: "Rocks",
      strength: 3,
      difficulty: "Easy",
      hook: "Warmer and deeper than its gin cousin — bittersweet and built for autumn.",
    },
    {
      slug: "sazerac",
      name: "Sazerac",
      tagline: "New Orleans, anise-kissed",
      color: "oklch(0.56 0.12 58)",
      colorSoft: "oklch(0.82 0.08 58)",
      ingredients: ["50ml rye whiskey", "1 sugar cube", "3 dashes Peychaud's bitters", "Absinthe rinse", "Lemon peel"],
      method: "Rinse a chilled glass with absinthe and discard. Stir rye, sugar and bitters with ice, strain in. Express lemon peel and discard.",
      glass: "Rocks",
      strength: 3,
      difficulty: "Advanced",
      hook: "Old as the cocktail itself — bracing, herbal and unmistakably New Orleans.",
    },
    {
      slug: "mint-julep",
      name: "Mint Julep",
      tagline: "Frost on the cup, mint in the nose",
      color: "oklch(0.72 0.09 120)",
      colorSoft: "oklch(0.86 0.06 120)",
      ingredients: ["60ml bourbon", "8–10 mint leaves", "10ml sugar syrup", "Crushed ice"],
      method: "Gently muddle mint with syrup, fill a julep cup with crushed ice, add bourbon and stir until frosted. Mound more ice and crown with a mint bouquet.",
      glass: "Julep cup",
      strength: 3,
      difficulty: "Medium",
      hook: "Bourbon's most refreshing ritual — and the taste of Derby day.",
    },
    {
      slug: "rusty-nail",
      name: "Rusty Nail",
      tagline: "Scotch meets heather honey",
      color: "oklch(0.52 0.12 70)",
      colorSoft: "oklch(0.8 0.08 70)",
      ingredients: ["45ml Scotch whisky", "20ml Drambuie", "Lemon twist"],
      method: "Build over ice in a rocks glass and stir briefly. Garnish with a lemon twist.",
      glass: "Rocks",
      strength: 3,
      difficulty: "Easy",
      hook: "Two ingredients, pure warmth — Scotch rounded out by honeyed liqueur.",
    },
    {
      slug: "whisky-highball",
      name: "Whisky Highball",
      tagline: "The art of the simple",
      color: "oklch(0.85 0.06 92)",
      colorSoft: "oklch(0.93 0.035 92)",
      ingredients: ["45ml Japanese whisky", "135ml soda water", "Plenty of ice", "Lemon peel"],
      method: "Build over ice in a chilled highball, add cold soda gently, and give it one slow stir. Express lemon peel.",
      glass: "Highball",
      strength: 1,
      difficulty: "Easy",
      hook: "Whisky, soda, ice and precision — light, crisp and endlessly drinkable.",
    },
    {
      slug: "irish-coffee",
      name: "Irish Coffee",
      tagline: "Hot, boozy, capped with cream",
      color: "oklch(0.35 0.05 55)",
      colorSoft: "oklch(0.72 0.06 60)",
      ingredients: ["40ml Irish whiskey", "90ml hot coffee", "15ml brown sugar syrup", "Lightly whipped cream"],
      method: "Stir whiskey, coffee and sugar in a warmed glass. Float cold cream over the back of a spoon so it sits on top.",
      glass: "Footed mug",
      strength: 2,
      difficulty: "Medium",
      hook: "Comfort engineered — sip the hot coffee through the cool cream.",
    },
    {
      slug: "hot-toddy",
      name: "Hot Toddy",
      tagline: "For when the cold gets in",
      color: "oklch(0.62 0.1 72)",
      colorSoft: "oklch(0.84 0.07 72)",
      ingredients: ["50ml Scotch whisky", "20ml honey", "20ml lemon juice", "Hot water", "Cinnamon & cloves"],
      method: "Stir honey and lemon with hot water until dissolved, add whisky. Garnish with a clove-studded lemon wheel and a cinnamon stick.",
      glass: "Mug",
      strength: 1,
      difficulty: "Easy",
      hook: "Soothing and spiced — the drink you reach for at the first chill.",
    },
    {
      slug: "penicillin",
      name: "Penicillin",
      tagline: "Honey, ginger, a curl of smoke",
      color: "oklch(0.72 0.11 82)",
      colorSoft: "oklch(0.87 0.07 82)",
      ingredients: ["50ml blended Scotch", "20ml lemon juice", "15ml honey-ginger syrup", "7.5ml Islay Scotch float"],
      method: "Shake blended Scotch, lemon and honey-ginger syrup with ice, strain over fresh ice. Float smoky Islay Scotch on top; garnish with candied ginger.",
      glass: "Rocks",
      strength: 2,
      difficulty: "Advanced",
      hook: "A modern classic — sweet heat finished with a wisp of peat.",
    },
    {
      slug: "paper-plane",
      name: "Paper Plane",
      tagline: "Equal parts, modern icon",
      color: "oklch(0.62 0.14 50)",
      colorSoft: "oklch(0.82 0.09 50)",
      ingredients: ["22ml bourbon", "22ml Aperol", "22ml Amaro Nonino", "22ml lemon juice"],
      method: "Shake all equally with ice, double-strain into a chilled coupe.",
      glass: "Coupe",
      strength: 2,
      difficulty: "Medium",
      hook: "Bittersweet, citrusy and impossibly balanced — the contemporary benchmark.",
    },
  ],
};

export const rum: Spirit = {
  name: "Rum",
  spiritTheme: "midnight",
  binomial: "Saccharum officinarum",
  abv: "37.5–50%",
  origin: "The Caribbean",
  intro:
    "Spirit of sugarcane, distilled from molasses or fresh-pressed juice and split into two worlds by the cask. White rum is bottled bright and unaged, all clean sugarcane snap; aged rum rests for years in oak, deepening into molasses, vanilla and spice. Between them lies the whole tropics in a glass.",
  character:
    "White rum is grassy, light and clean — a crisp canvas built for citrus and ice. Aged and dark rums turn rich and rounded, with molasses sweetness, vanilla and oak from long years in the barrel. The lighter styles refresh; the older ones reward slow sipping.",
  notes: [
    { label: "Sugarcane", detail: "Grassy, sweet — the spirit's living root" },
    { label: "Vanilla", detail: "Soft and creamy, drawn from the oak cask" },
    { label: "Oak", detail: "Warm spice and colour from years of ageing" },
    { label: "Tropical fruit", detail: "Banana, pineapple and ripe mango esters" },
    { label: "Baking spice", detail: "Cinnamon, clove and nutmeg in the finish" },
  ],
  serves: [
    {
      name: "Neat",
      blurb:
        "How to drink an aged sipping rum. A small pour at room temperature in a tulip glass — let the molasses and oak unfold.",
      glass: "neat",
    },
    {
      name: "On the rocks",
      blurb:
        "One large cube and a wedge of lime. Chills a dark rum gently and softens the sweeter, richer bottlings.",
      glass: "rocks",
    },
    {
      name: "Daiquiri-style",
      blurb:
        "White rum, lime and a little sugar, shaken hard and served up. The purest test of a light rum's quality.",
      glass: "coupe",
    },
    {
      name: "Rum & Cola",
      blurb:
        "Built over ice in a highball with cold cola and a squeeze of lime. The easiest long drink in the tropics.",
      glass: "highball",
    },
  ],
  mixers: [
    { name: "Cola", note: "Caramel sweetness, builds the Cuba Libre", color: "oklch(0.32 0.06 50)" },
    { name: "Fresh lime", note: "Sharp green acid, rum's closest partner", color: "oklch(0.88 0.13 130)" },
    { name: "Ginger beer", note: "Spicy and cloudy — the Dark & Stormy half", color: "oklch(0.85 0.07 85)" },
    { name: "Pineapple juice", note: "Tropical, frothy, sweet-tart", color: "oklch(0.86 0.13 95)" },
    { name: "Coconut cream", note: "Rich and silky, the Piña Colada base", color: "oklch(0.96 0.02 110)" },
    { name: "Orgeat", note: "Almond syrup, the Mai Tai's secret", color: "oklch(0.92 0.03 90)" },
    { name: "Mint", note: "Cool and fresh, muddled for a Mojito", color: "oklch(0.78 0.13 145)" },
    { name: "Soda water", note: "Clean lengthener, keeps a Mojito crisp", color: "oklch(0.98 0.004 220)" },
    { name: "Demerara syrup", note: "Deep cane sweetness for tiki drinks", color: "oklch(0.55 0.1 65)" },
    { name: "Angostura bitters", note: "Aromatic spice to season the sweetness", color: "oklch(0.42 0.12 32)" },
  ],
  cocktails: [
    {
      slug: "daiquiri",
      name: "Daiquiri",
      tagline: "Three ingredients, total clarity",
      color: "oklch(0.95 0.03 110)",
      colorSoft: "oklch(0.97 0.018 110)",
      ingredients: ["60ml white rum", "25ml lime juice", "15ml sugar syrup", "Lime wheel"],
      method: "Shake hard with ice until ice-cold, double-strain into a chilled coupe. Garnish with a lime wheel.",
      glass: "Coupe",
      strength: 2,
      difficulty: "Easy",
      hook: "Rum, lime, sugar in perfect balance — the test every white rum must pass.",
    },
    {
      slug: "mojito",
      name: "Mojito",
      tagline: "Mint, lime and fizz",
      color: "oklch(0.9 0.08 140)",
      colorSoft: "oklch(0.94 0.05 140)",
      ingredients: ["50ml white rum", "25ml lime juice", "15ml sugar syrup", "8 mint leaves", "Soda water"],
      method: "Gently muddle mint with sugar and lime, add rum and crushed ice, churn, top with soda. Mint sprig.",
      glass: "Highball",
      strength: 1,
      difficulty: "Medium",
      hook: "Havana's cooler — herbal, tall and endlessly refreshing.",
    },
    {
      slug: "mai-tai",
      name: "Mai Tai",
      tagline: "The tiki benchmark",
      color: "oklch(0.7 0.13 70)",
      colorSoft: "oklch(0.86 0.08 70)",
      ingredients: ["30ml aged rum", "30ml white rum", "15ml orange curaçao", "15ml orgeat", "20ml lime juice"],
      method: "Shake all with crushed ice, pour unstrained into a rocks glass. Spent lime shell and a mint sprig.",
      glass: "Rocks",
      strength: 3,
      difficulty: "Advanced",
      hook: "Almond, orange and rum layered deep — the drink that defined tiki.",
    },
    {
      slug: "dark-and-stormy",
      name: "Dark & Stormy",
      tagline: "Storm cloud in a glass",
      color: "oklch(0.5 0.1 60)",
      colorSoft: "oklch(0.78 0.08 60)",
      ingredients: ["50ml dark rum", "100ml ginger beer", "15ml lime juice", "Lime wedge"],
      method: "Build ginger beer over ice in a highball, float dark rum on top so it bleeds down. Squeeze lime.",
      glass: "Highball",
      strength: 2,
      difficulty: "Easy",
      hook: "Spicy ginger and dark rum, poured so the storm rolls in from the top.",
    },
    {
      slug: "pina-colada",
      name: "Piña Colada",
      tagline: "The taste of the tropics",
      color: "oklch(0.92 0.05 95)",
      colorSoft: "oklch(0.95 0.03 95)",
      ingredients: ["60ml white rum", "60ml pineapple juice", "30ml coconut cream", "Pineapple wedge"],
      method: "Blend with a cup of crushed ice until smooth, pour into a hurricane glass. Pineapple and a cherry.",
      glass: "Hurricane",
      strength: 1,
      difficulty: "Easy",
      hook: "Creamy, sweet and unapologetic — a beach holiday you can drink.",
    },
    {
      slug: "cuba-libre",
      name: "Cuba Libre",
      tagline: "Rum and cola, done right",
      color: "oklch(0.38 0.07 50)",
      colorSoft: "oklch(0.72 0.06 55)",
      ingredients: ["50ml white rum", "120ml cola", "15ml lime juice", "Lime wedge"],
      method: "Build over ice in a highball, squeeze and drop in the lime, add cola, stir once gently.",
      glass: "Highball",
      strength: 1,
      difficulty: "Easy",
      hook: "Lime is the difference between this and a plain rum and coke — don't skip it.",
    },
    {
      slug: "rum-old-fashioned",
      name: "Rum Old Fashioned",
      tagline: "Aged rum, slow and rich",
      color: "oklch(0.52 0.11 62)",
      colorSoft: "oklch(0.8 0.08 62)",
      ingredients: ["60ml aged rum", "10ml demerara syrup", "2 dashes Angostura bitters", "Orange peel"],
      method: "Stir rum, syrup and bitters over a large cube until chilled. Express orange peel over the top.",
      glass: "Rocks",
      strength: 3,
      difficulty: "Easy",
      hook: "Molasses depth and oak, seasoned with bitters — sipping rum's finest frame.",
    },
    {
      slug: "painkiller",
      name: "Painkiller",
      tagline: "Tropical, creamy, nutmeg-dusted",
      color: "oklch(0.82 0.1 80)",
      colorSoft: "oklch(0.9 0.06 80)",
      ingredients: ["60ml dark rum", "60ml pineapple juice", "30ml orange juice", "20ml coconut cream", "Grated nutmeg"],
      method: "Shake all with ice, pour over crushed ice in a tall glass. Dust generously with fresh nutmeg.",
      glass: "Highball",
      strength: 2,
      difficulty: "Easy",
      hook: "The Painkiller earns its name — lush, fruity and softly spiced.",
    },
    {
      slug: "hurricane",
      name: "Hurricane",
      tagline: "New Orleans in technicolour",
      color: "oklch(0.62 0.16 35)",
      colorSoft: "oklch(0.82 0.1 38)",
      ingredients: ["50ml dark rum", "50ml white rum", "50ml passion fruit syrup", "25ml lime juice", "25ml orange juice"],
      method: "Shake all with ice, pour into a hurricane glass over fresh ice. Orange slice and a cherry.",
      glass: "Hurricane",
      strength: 3,
      difficulty: "Medium",
      hook: "Passion fruit and a double hit of rum — bright, boozy and tropical.",
    },
    {
      slug: "ti-punch",
      name: "Ti' Punch",
      tagline: "Rhum agricole, stripped bare",
      color: "oklch(0.9 0.07 120)",
      colorSoft: "oklch(0.94 0.04 120)",
      ingredients: ["60ml rhum agricole blanc", "1 bar spoon cane syrup", "Lime disc"],
      method: "Squeeze a thick lime disc into a glass, add cane syrup and rhum. Stir; ice optional — chacun prépare sa propre mort.",
      glass: "Rocks",
      strength: 3,
      difficulty: "Easy",
      hook: "The French Caribbean ritual — grassy agricole, lime and cane, nothing else.",
    },
    {
      slug: "rum-punch",
      name: "Rum Punch",
      tagline: "One of sour, two of sweet…",
      color: "oklch(0.68 0.15 45)",
      colorSoft: "oklch(0.85 0.09 45)",
      ingredients: ["60ml aged rum", "20ml lime juice", "40ml pineapple juice", "10ml grenadine", "Angostura bitters"],
      method: "Shake with ice, pour over crushed ice. Dash bitters, grate nutmeg, garnish with fruit.",
      glass: "Highball",
      strength: 2,
      difficulty: "Easy",
      hook: "The old island rhyme made drinkable — sour, sweet, strong and weak in balance.",
    },
    {
      slug: "el-presidente",
      name: "El Presidente",
      tagline: "Havana's elegant aperitif",
      color: "oklch(0.74 0.1 55)",
      colorSoft: "oklch(0.87 0.06 55)",
      ingredients: ["50ml white rum", "20ml dry vermouth", "10ml orange curaçao", "1 bar spoon grenadine"],
      method: "Stir with ice until well chilled, strain into a chilled coupe. Orange twist.",
      glass: "Coupe",
      strength: 2,
      difficulty: "Medium",
      hook: "A 1920s Cuban classic — dry, refined and far more sophisticated than it sounds.",
    },
  ],
};

export const tequila: Spirit = {
  name: "Tequila",
  spiritTheme: "botanic",
  binomial: "Agave tequilana",
  abv: "38–40%",
  origin: "Jalisco, Mexico",
  intro:
    "Distilled from the roasted heart of the blue agave, tequila is shaped above all by time in oak. Blanco is bottled unaged and bright; reposado rests two to twelve months for a gentle gold; añejo sleeps one to three years into deep amber. One plant, three ages, three very different spirits.",
  character:
    "Blanco is bright and vegetal — raw cooked agave, citrus and cracked white pepper, mineral and clean. With age it turns rounder and richer: reposado adds soft vanilla and caramel, while añejo leans into oak, dried fruit and warm spice. The young styles shake into bright cocktails; the aged ones reward sipping like a fine whisky.",
  notes: [
    { label: "Agave", detail: "Roasted, sweet-vegetal — the cooked piña itself" },
    { label: "Citrus", detail: "Bright lime and grapefruit zest" },
    { label: "White pepper", detail: "Peppery bite, the blanco signature" },
    { label: "Earth & mineral", detail: "Wet stone and soil, the terroir of the lowlands" },
    { label: "Oak", detail: "Vanilla, caramel and spice from the barrel" },
  ],
  serves: [
    {
      name: "Neat",
      blurb:
        "How a good tequila is meant to be drunk — no salt, no lime. A small pour at room temperature, sipped slowly to let the agave show.",
      glass: "neat",
    },
    {
      name: "On the rocks",
      blurb:
        "One large cube and a grapefruit twist. Chills a reposado gently and tames the heat of a higher-proof blanco.",
      glass: "rocks",
    },
    {
      name: "Paloma",
      blurb:
        "Tequila lengthened with grapefruit soda and a pinch of salt over ice. Mexico's real everyday drink — far more common than the Margarita.",
      glass: "highball",
    },
    {
      name: "Margarita-style",
      blurb:
        "Tequila, lime and orange liqueur, shaken hard and served up or on the rocks with a salt rim. The benchmark agave cocktail.",
      glass: "coupe",
    },
  ],
  mixers: [
    { name: "Fresh lime", note: "Sharp green acid, agave's closest partner", color: "oklch(0.88 0.13 130)" },
    { name: "Grapefruit soda", note: "Tart and fizzy, builds the Paloma", color: "oklch(0.9 0.07 50)" },
    { name: "Triple sec", note: "Orange liqueur, the Margarita's backbone", color: "oklch(0.96 0.02 95)" },
    { name: "Agave syrup", note: "Rounds the edges, ties back to the plant", color: "oklch(0.78 0.09 75)" },
    { name: "Orange juice", note: "Sweet and bright, the Sunrise base", color: "oklch(0.78 0.15 65)" },
    { name: "Grenadine", note: "Pomegranate-red, sinks for the sunrise", color: "oklch(0.5 0.18 25)" },
    { name: "Tomato juice", note: "Savoury and rich, builds a Bloody Maria", color: "oklch(0.5 0.16 30)" },
    { name: "Pineapple juice", note: "Tropical sweetness, loves a mezcal edge", color: "oklch(0.86 0.13 95)" },
    { name: "Soda water", note: "Clean lengthener, keeps a Ranch Water crisp", color: "oklch(0.98 0.004 220)" },
    { name: "Mezcal", note: "Smoky agave cousin, a float for depth", color: "oklch(0.95 0.012 110)" },
  ],
  cocktails: [
    {
      slug: "margarita",
      name: "Margarita",
      tagline: "The benchmark agave sour",
      color: "oklch(0.9 0.09 120)",
      colorSoft: "oklch(0.94 0.05 120)",
      ingredients: ["50ml blanco tequila", "25ml lime juice", "20ml triple sec", "Salt rim"],
      method: "Shake hard with ice, strain into a salt-rimmed glass over fresh ice (or up). Lime wheel.",
      glass: "Rocks",
      strength: 2,
      difficulty: "Easy",
      hook: "Tart, salty and perfectly balanced — the drink that made tequila famous.",
    },
    {
      slug: "tommys-margarita",
      name: "Tommy's Margarita",
      tagline: "Agave instead of orange",
      color: "oklch(0.91 0.08 115)",
      colorSoft: "oklch(0.95 0.045 115)",
      ingredients: ["60ml blanco tequila", "30ml lime juice", "15ml agave syrup"],
      method: "Shake with ice, strain into a chilled rocks glass over fresh ice. No salt, no orange — lime wheel.",
      glass: "Rocks",
      strength: 2,
      difficulty: "Easy",
      hook: "A modern San Francisco classic that lets the agave, not the curaçao, lead.",
    },
    {
      slug: "paloma",
      name: "Paloma",
      tagline: "Mexico's everyday long drink",
      color: "oklch(0.88 0.08 50)",
      colorSoft: "oklch(0.93 0.05 50)",
      ingredients: ["50ml blanco tequila", "15ml lime juice", "Pinch of salt", "Grapefruit soda"],
      method: "Build tequila, lime and salt over ice in a highball, top with grapefruit soda. Grapefruit wedge.",
      glass: "Highball",
      strength: 1,
      difficulty: "Easy",
      hook: "More common than the Margarita at home — tart, salty and endlessly refreshing.",
    },
    {
      slug: "tequila-sunrise",
      name: "Tequila Sunrise",
      tagline: "Sunrise in a glass",
      color: "oklch(0.72 0.16 55)",
      colorSoft: "oklch(0.86 0.1 55)",
      ingredients: ["50ml blanco tequila", "120ml orange juice", "10ml grenadine", "Orange slice"],
      method: "Build tequila and orange juice over ice, then pour grenadine down the inside so it sinks and bleeds up.",
      glass: "Highball",
      strength: 1,
      difficulty: "Easy",
      hook: "The grenadine sunrise does the work — a 1970s icon that still looks the part.",
    },
    {
      slug: "oaxacan-old-fashioned",
      name: "Oaxacan Old Fashioned",
      tagline: "Agave, oak and smoke",
      color: "oklch(0.6 0.11 65)",
      colorSoft: "oklch(0.82 0.08 65)",
      ingredients: ["45ml reposado tequila", "15ml mezcal", "1 bar spoon agave syrup", "2 dashes Angostura bitters", "Orange peel"],
      method: "Stir all over a large cube until chilled. Express orange peel and flame it over the glass for aroma.",
      glass: "Rocks",
      strength: 3,
      difficulty: "Medium",
      hook: "The agave answer to the Old Fashioned — rich, spirit-forward and lightly smoky.",
    },
    {
      slug: "ranch-water",
      name: "Ranch Water",
      tagline: "Tequila, lime, fizz",
      color: "oklch(0.95 0.025 130)",
      colorSoft: "oklch(0.97 0.015 130)",
      ingredients: ["50ml blanco tequila", "15ml lime juice", "Topo Chico or soda water", "Lime wedge"],
      method: "Build over ice in a highball, top with sparkling mineral water, squeeze in the lime.",
      glass: "Highball",
      strength: 1,
      difficulty: "Easy",
      hook: "West Texas minimalism — barely a cocktail, and all the better for it.",
    },
    {
      slug: "bloody-maria",
      name: "Bloody Maria",
      tagline: "The Bloody Mary's agave sister",
      color: "oklch(0.5 0.16 32)",
      colorSoft: "oklch(0.78 0.1 32)",
      ingredients: ["50ml blanco tequila", "120ml tomato juice", "15ml lime juice", "Hot sauce, Worcestershire", "Celery salt & pepper"],
      method: "Roll between two glasses with ice to mix without frothing, pour into a tall glass. Garnish generously.",
      glass: "Highball",
      strength: 1,
      difficulty: "Medium",
      hook: "Tequila swaps in for vodka and brings a savoury, peppery edge to brunch.",
    },
    {
      slug: "el-diablo",
      name: "El Diablo",
      tagline: "Ginger, cassis and lime",
      color: "oklch(0.5 0.15 350)",
      colorSoft: "oklch(0.78 0.1 350)",
      ingredients: ["45ml reposado tequila", "15ml crème de cassis", "15ml lime juice", "Ginger beer"],
      method: "Shake tequila, cassis and lime with ice, strain into an ice-filled highball, top with ginger beer.",
      glass: "Highball",
      strength: 2,
      difficulty: "Easy",
      hook: "Spicy ginger and dark berry — a tequila highball with a devilish streak.",
    },
    {
      slug: "matador",
      name: "Matador",
      tagline: "Pineapple meets agave",
      color: "oklch(0.84 0.13 95)",
      colorSoft: "oklch(0.91 0.08 95)",
      ingredients: ["45ml blanco tequila", "60ml pineapple juice", "15ml lime juice", "Pineapple wedge"],
      method: "Shake with ice, strain over fresh ice in a rocks glass. Garnish with a pineapple wedge.",
      glass: "Rocks",
      strength: 1,
      difficulty: "Easy",
      hook: "Tropical and tart — pineapple and lime make blanco sing.",
    },
    {
      slug: "mezcal-margarita",
      name: "Mezcal Margarita",
      tagline: "A Margarita with smoke",
      color: "oklch(0.89 0.09 118)",
      colorSoft: "oklch(0.94 0.05 118)",
      ingredients: ["40ml blanco tequila", "20ml mezcal", "25ml lime juice", "20ml agave syrup", "Chilli-salt rim"],
      method: "Shake all with ice, strain over fresh ice in a glass rimmed with chilli salt. Lime wheel.",
      glass: "Rocks",
      strength: 2,
      difficulty: "Medium",
      hook: "The classic with a curl of smoke — a chilli rim takes it further.",
    },
    {
      slug: "cantarito",
      name: "Cantarito",
      tagline: "The Paloma, gone full citrus",
      color: "oklch(0.82 0.12 60)",
      colorSoft: "oklch(0.9 0.07 60)",
      ingredients: ["50ml blanco tequila", "Lime, lemon & orange juice", "Pinch of salt", "Grapefruit soda"],
      method: "Build tequila, the three citrus juices and salt over ice in a salt-rimmed clay cup, top with grapefruit soda.",
      glass: "Clay cup",
      strength: 1,
      difficulty: "Easy",
      hook: "Served in a clay cantarito that keeps it cold and adds an earthy note — a Jalisco street classic.",
    },
    {
      slug: "tequila-sour",
      name: "Tequila Sour",
      tagline: "Silky, tart, agave-led",
      color: "oklch(0.86 0.11 92)",
      colorSoft: "oklch(0.92 0.06 92)",
      ingredients: ["50ml blanco tequila", "25ml lime juice", "20ml agave syrup", "Egg white", "Angostura bitters"],
      method: "Dry-shake with egg white, then shake with ice, strain over fresh ice. Dash bitters on the foam.",
      glass: "Rocks",
      strength: 2,
      difficulty: "Medium",
      hook: "The sour template built on agave — a cloud of foam over bright lime.",
    },
  ],
};

export const vodka: Spirit = {
  name: "Vodka",
  spiritTheme: "indigo",
  binomial: "Solanum tuberosum",
  abv: "37.5–40%",
  origin: "Russia & Poland",
  intro:
    "Distilled to near-neutrality and filtered until it's clean as water, vodka is defined less by what's added than by what it's made from. Grain vodkas (wheat, rye) lean crisp and peppery; potato vodka is rounder and creamier; grape and other bases bring a faint fruit softness. The base is the whole signature.",
  character:
    "Vodka's art is restraint — smooth, clean and all but flavourless by design. Yet the base ingredient still whispers through: wheat is soft and slightly sweet, rye dry and peppery, potato full and oily, grape gently fruity. Where gin announces itself with botanicals, vodka is the clean canvas every other ingredient gets to paint on.",
  notes: [
    { label: "Clean alcohol", detail: "Crisp, neutral warmth — the whole point" },
    { label: "Subtle grain", detail: "Soft wheat or peppery rye underneath" },
    { label: "Faint sweetness", detail: "A gentle, rounded note on the mid-palate" },
    { label: "Mineral", detail: "Cool, stony edge from the water" },
    { label: "White pepper", detail: "A whisper of spice on the finish" },
  ],
  serves: [
    {
      name: "Neat, chilled",
      blurb:
        "Straight from the freezer into a chilled glass, no ice to dilute. The way it's drunk across Eastern Europe — viscous, cold and clean.",
      glass: "neat",
    },
    {
      name: "On the rocks",
      blurb:
        "One large cube and a twist of lemon. Opens up a characterful potato or rye vodka as it slowly chills.",
      glass: "rocks",
    },
    {
      name: "Soda & twist",
      blurb:
        "Lengthened with cold soda over ice and a citrus twist. The cleanest possible long drink — lets the base vodka speak.",
      glass: "highball",
    },
    {
      name: "Dirty Martini",
      blurb:
        "Vodka, a little dry vermouth and a splash of olive brine, stirred ice-cold. Savoury, bracing and crystal clear.",
      glass: "coupe",
    },
  ],
  mixers: [
    { name: "Tonic water", note: "Quinine bitterness, a clean long drink", color: "oklch(0.97 0.012 200)" },
    { name: "Soda water", note: "Pure lengthener, keeps it crisp", color: "oklch(0.98 0.004 220)" },
    { name: "Cranberry juice", note: "Tart and ruby — the Cosmo's colour", color: "oklch(0.5 0.17 20)" },
    { name: "Tomato juice", note: "Savoury and thick, builds a Bloody Mary", color: "oklch(0.5 0.16 30)" },
    { name: "Ginger beer", note: "Spicy and cloudy, the Mule's half", color: "oklch(0.85 0.07 85)" },
    { name: "Fresh lime", note: "Sharp green acid, the classic balancer", color: "oklch(0.88 0.13 130)" },
    { name: "Coffee liqueur", note: "Roasted and sweet, builds a Russian", color: "oklch(0.28 0.05 50)" },
    { name: "Cold espresso", note: "Bitter crema, the Espresso Martini base", color: "oklch(0.3 0.04 55)" },
    { name: "Dry vermouth", note: "Herbal and dry — the Martini's other half", color: "oklch(0.92 0.05 105)" },
    { name: "Orange juice", note: "Sweet and bright, builds a Screwdriver", color: "oklch(0.78 0.15 65)" },
  ],
  cocktails: [
    {
      slug: "espresso-martini",
      name: "Espresso Martini",
      tagline: "Wide awake, then asleep",
      color: "oklch(0.32 0.04 55)",
      colorSoft: "oklch(0.6 0.05 55)",
      ingredients: ["50ml vodka", "30ml fresh espresso", "20ml coffee liqueur", "10ml sugar syrup"],
      method: "Shake hard with ice until frothy, double-strain into a chilled coupe. Three coffee beans.",
      glass: "Coupe",
      strength: 2,
      difficulty: "Medium",
      hook: "Rich, bittersweet and crowned with foam — the 1980s classic that never left.",
    },
    {
      slug: "moscow-mule",
      name: "Moscow Mule",
      tagline: "Spiced, fizzy, in copper",
      color: "oklch(0.86 0.07 88)",
      colorSoft: "oklch(0.92 0.05 88)",
      ingredients: ["50ml vodka", "15ml lime juice", "Ginger beer", "Lime wedge"],
      method: "Build vodka and lime over ice in a copper mug, top with ginger beer. Lime wedge and a mint sprig.",
      glass: "Copper mug",
      strength: 1,
      difficulty: "Easy",
      hook: "The drink that sold America on vodka — ginger heat in a frosted copper mug.",
    },
    {
      slug: "cosmopolitan",
      name: "Cosmopolitan",
      tagline: "Pink, tart and iconic",
      color: "oklch(0.62 0.16 18)",
      colorSoft: "oklch(0.82 0.1 18)",
      ingredients: ["45ml citron vodka", "15ml triple sec", "15ml cranberry juice", "10ml lime juice"],
      method: "Shake with ice, double-strain into a chilled coupe. Flamed orange twist.",
      glass: "Coupe",
      strength: 2,
      difficulty: "Easy",
      hook: "Tart, dry and unmistakably pink — the 1990s' most famous cocktail.",
    },
    {
      slug: "bloody-mary",
      name: "Bloody Mary",
      tagline: "Savoury brunch in a glass",
      color: "oklch(0.5 0.16 30)",
      colorSoft: "oklch(0.78 0.1 30)",
      ingredients: ["50ml vodka", "120ml tomato juice", "15ml lemon juice", "Worcestershire, Tabasco", "Celery salt & pepper"],
      method: "Roll between two glasses with ice to mix without frothing, pour into a tall glass. Celery and lemon.",
      glass: "Highball",
      strength: 1,
      difficulty: "Medium",
      hook: "Spicy, savoury and endlessly customised — the definitive morning-after drink.",
    },
    {
      slug: "white-russian",
      name: "White Russian",
      tagline: "Coffee, cream, vodka",
      color: "oklch(0.72 0.05 70)",
      colorSoft: "oklch(0.86 0.04 70)",
      ingredients: ["50ml vodka", "25ml coffee liqueur", "25ml fresh cream"],
      method: "Build vodka and coffee liqueur over ice in a rocks glass, float cream and stir gently if you like.",
      glass: "Rocks",
      strength: 2,
      difficulty: "Easy",
      hook: "Dessert that drinks back — the Dude abides.",
    },
    {
      slug: "vodka-martini",
      name: "Vodka Martini",
      tagline: "Shaken or stirred",
      color: "oklch(0.96 0.01 200)",
      colorSoft: "oklch(0.98 0.006 200)",
      ingredients: ["60ml vodka", "10ml dry vermouth", "Lemon twist or olive"],
      method: "Stir (or shake) with ice until ice-cold, strain into a chilled coupe. Garnish to taste.",
      glass: "Coupe",
      strength: 3,
      difficulty: "Easy",
      hook: "Crisp, clean and bracingly cold — the clearest mirror a vodka can be poured into.",
    },
    {
      slug: "vodka-tonic",
      name: "Vodka Tonic",
      tagline: "Crisp and effortless",
      color: "oklch(0.96 0.015 200)",
      colorSoft: "oklch(0.98 0.01 200)",
      ingredients: ["50ml vodka", "150ml tonic water", "Lime wedge", "Plenty of ice"],
      method: "Build over ice in a highball, add tonic gently, squeeze in the lime.",
      glass: "Highball",
      strength: 1,
      difficulty: "Easy",
      hook: "The blank-canvas long drink — clean, dry and as simple as it gets.",
    },
    {
      slug: "screwdriver",
      name: "Screwdriver",
      tagline: "Vodka meets orange",
      color: "oklch(0.78 0.15 65)",
      colorSoft: "oklch(0.88 0.09 65)",
      ingredients: ["50ml vodka", "120ml orange juice", "Orange slice", "Plenty of ice"],
      method: "Build over ice in a highball, stir gently. Garnish with an orange slice.",
      glass: "Highball",
      strength: 1,
      difficulty: "Easy",
      hook: "Two ingredients, zero fuss — the original breakfast cocktail.",
    },
    {
      slug: "sea-breeze",
      name: "Sea Breeze",
      tagline: "Cranberry, grapefruit, ice",
      color: "oklch(0.6 0.15 22)",
      colorSoft: "oklch(0.8 0.1 22)",
      ingredients: ["50ml vodka", "90ml cranberry juice", "30ml grapefruit juice", "Lime wedge"],
      method: "Build over ice in a highball, stir to combine. Lime wedge.",
      glass: "Highball",
      strength: 1,
      difficulty: "Easy",
      hook: "Tart, fruity and pink-orange — a 1980s patio staple.",
    },
    {
      slug: "lemon-drop",
      name: "Lemon Drop Martini",
      tagline: "Sour candy, all grown up",
      color: "oklch(0.9 0.11 100)",
      colorSoft: "oklch(0.94 0.06 100)",
      ingredients: ["50ml citron vodka", "20ml triple sec", "20ml lemon juice", "10ml sugar syrup", "Sugar rim"],
      method: "Shake with ice, double-strain into a sugar-rimmed coupe. Lemon twist.",
      glass: "Coupe",
      strength: 2,
      difficulty: "Easy",
      hook: "Bright, tart and just sweet enough — a dessert martini that earns its sugar rim.",
    },
    {
      slug: "black-russian",
      name: "Black Russian",
      tagline: "Two ingredients, late night",
      color: "oklch(0.3 0.05 55)",
      colorSoft: "oklch(0.58 0.05 55)",
      ingredients: ["50ml vodka", "25ml coffee liqueur", "Large ice cube"],
      method: "Build over a large cube in a rocks glass, stir briefly.",
      glass: "Rocks",
      strength: 2,
      difficulty: "Easy",
      hook: "The White Russian before the cream — dark, sweet and simple.",
    },
    {
      slug: "vodka-gimlet",
      name: "Vodka Gimlet",
      tagline: "Clean, tart, to the point",
      color: "oklch(0.92 0.07 128)",
      colorSoft: "oklch(0.95 0.04 128)",
      ingredients: ["60ml vodka", "20ml lime cordial", "Lime wheel"],
      method: "Shake with ice, double-strain into a chilled coupe. Lime wheel.",
      glass: "Coupe",
      strength: 2,
      difficulty: "Easy",
      hook: "The gin Gimlet's cooler cousin — two ingredients and total clarity.",
    },
  ],
};

/** All spirits, keyed by URL slug. */
export const spirits: Record<string, Spirit> = {
  gin,
  whisky,
  rum,
  tequila,
  vodka,
};

/** Look up a spirit by its URL slug, or undefined if none exists. */
export function getSpirit(slug: string): Spirit | undefined {
  return spirits[slug];
}
